name: thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm
  - pyyaml
  - ipykernel
  - jupyter
  - pip:
      - wandb
      - yfinance
      - powerlaw